# Navigation
menu:
  Home: index.html
  Documentation: //docs.rainmeter.net/
  Discover: discover.html
  Community: //forum.rainmeter.net

# Downloads
downloads:
  final:
    versionName: '4.0 Final Release'
    buildNumber: 'r2746'
    downloadURL: https://github.com/rainmeter/rainmeter/releases/download/v4.0.0.2746/Rainmeter-4.0.exe
    mirrorURL: https://builds.rainmeter.net/Rainmeter-4.0.exe
    releaseNotesURL: release-4-0.html
  beta:
    versionName: '4.1 Beta Release'
    buildNumber: 'r2858'
    downloadURL: https://github.com/rainmeter/rainmeter/releases/download/v4.1.0.2858/Rainmeter-4.1-r2858-beta.exe
    mirrorURL: https://builds.rainmeter.net/Rainmeter-4.1-r2858-beta.exe
    releaseNotesURL: beta-4-1.html

# News block
news:
  - title: 'A fresh coat of paint!'
    url: beta-4-1.html
    date: 'August 27, 2017'
  - title: 'Rainmeter 4.1 Beta Release'
    url: beta-4-1.html
    date: 'July 28, 2017'
  - title: 'Rainmeter 4.0 Final Release'
    url: release-4-0.html
    date: 'July 28, 2017'

# skin carousel
carousel:
  - link: example.com
    imageURL: http://via.placeholder.com/445x250
    title: 'Example 1'
    author: 'test'
  - link: example.com/2
    imageURL: http://via.placeholder.com/445x250/6691FF/FFFFFF
    title: 'Example 2'
    author: 'test'

# Showcase gallery
gallery:
  - link: https://hiphopium.deviantart.com/art/Momento-698402825
    thumbnailURL: img/showcase/momento_by_hiphopium.jpg
    imageURL: img/showcase/momento_by_hiphopium.jpg
    title: 'Momento'
    author: 'HipHopium'
  - link: https://www.deviantart.com/art/Rime-Rainmeter-642132946
    thumbnailURL: img/showcase/rime_rainmeter_by_iroaseta.png
    imageURL: img/showcase/rime_rainmeter_by_iroaseta.png
    title: 'Rime Rainmeter'
    author: 'Iroaseta'
  - link: https://www.reddit.com/r/Rainmeter/comments/60qz2m/cyberpunk_coffee/
    thumbnailURL: img/showcase/cyberpunk_coffee_by_labr4t_thumb.png
    imageURL: img/showcase/cyberpunk_coffee_by_labr4t.gif
    title: 'Cyberpunk Coffee'
    author: 'Labr4t'
  - link: https://www.reddit.com/r/Rainmeter/comments/6fi83s/blue_and_simple/
    thumbnailURL: img/showcase/blue_and_simple_by_keeWend.jpg
    imageURL: img/showcase/blue_and_simple_by_keeWend.jpg
    title: 'Blue and Simple'
    author: 'keeWend'
  - link: https://www.reddit.com/user/khanhas
    thumbnailURL: img/showcase/polybar_by_khanhas.png
    imageURL: img/showcase/polybar_by_khanhas.png
    title: 'polybar'
    author: 'khanhas'
  - link: https://iroaseta.deviantart.com/art/Geometry-Rainmeter-666821772
    thumbnailURL: img/showcase/geometry_rainmeter_by_iroaseta.png
    imageURL: img/showcase/geometry_rainmeter_by_iroaseta.png
    title: 'Geometry Rainmeter'
    author: 'Iroaseta'
