# Header
menu:
  Home: index.html
  Documentation: //docs.rainmeter.net/
  Discover: discover.html
  Community: //forum.rainmeter.net

# Downloads
downloads:
  final:
    versionName: '4.0 Final Release'
    buildNumber: 'r2746'
    downloadURL: https://github.com/rainmeter/rainmeter/releases/download/v4.0.0.2746/Rainmeter-4.0.exe
    mirrorURL: https://builds.rainmeter.net/Rainmeter-4.0.exe
    releaseNotesURL: release-4-0.html
  beta:
    versionName: '4.1 Beta Release'
    buildNumber: 'r2858'
    downloadURL: https://github.com/rainmeter/rainmeter/releases/download/v4.1.0.2858/Rainmeter-4.1-r2858-beta.exe
    mirrorURL: https://builds.rainmeter.net/Rainmeter-4.1-r2858-beta.exe
    releaseNotesURL: beta-4-1.html

# News block
news:
  - title: 'A fresh coat of paint!'
    url: beta-4-1.html
    date: 'August 27, 2017'
  - title: 'Rainmeter 4.1 Beta Release'
    url: beta-4-1.html
    date: 'July 28, 2017'
  - title: 'Rainmeter 4.0 Final Release'
    url: release-4-0.html
    date: 'July 28, 2017'
  - title: 'Updates to Localization Files'
    url: https://forum.rainmeter.net/viewtopic.php?f=13&t=25139
    date: 'July 28, 2017'

# skin carousel
carousel:
  - link: example.com
    imageURL: http://via.placeholder.com/445x250
    title: 'Example 1'
    author: 'test'
  - link: example.com/2
    imageURL: http://via.placeholder.com/445x250/6691FF/FFFFFF
    title: 'Example 2'
    author: 'test'

# Showcase gallery
gallery:
  - link: example.com
    thumbnailURL: http://via.placeholder.com/445x250
    imageURL: http://via.placeholder.com/1920x1080.jpg
    title: 'Example 1'
    author: 'test'
  - link: example.com
    thumbnailURL: http://via.placeholder.com/445x250
    imageURL: http://via.placeholder.com/1920x1080.jpg
    title: 'Example 2'
    author: 'test'
  - link: example.com
    thumbnailURL: http://via.placeholder.com/445x250
    imageURL: http://via.placeholder.com/1920x1080.jpg
    title: 'Example 3'
    author: 'test'
  - link: example.com
    thumbnailURL: http://via.placeholder.com/445x250
    imageURL: http://via.placeholder.com/1920x1080.jpg
    title: 'Example 4'
    author: 'test'
  - link: example.com
    thumbnailURL: http://via.placeholder.com/445x250
    imageURL: http://via.placeholder.com/1920x1080.jpg
    title: 'Example 5'
    author: 'test'
  - link: example.com
    thumbnailURL: http://via.placeholder.com/445x250
    imageURL: http://via.placeholder.com/1920x1080.jpg
    title: 'Example 6'
    author: 'test'
